name: Test install-elvish-packages
description: Tests for install-elvish-packages.

runs:
  using: composite
  steps:
    - uses: giancosta86/gauntlet/actions/setup-elvish-action@v1

    - shell: bash
      working-directory: ${{ github.action_path }}
      run: elvish setup.elv

    - shell: elvish {0}
      run: echo 🎭 Installing the Velvet package from the main branch...

    - uses: ./actions/install-elvish-packages
      with:
        packages: github.com/giancosta86/velvet

    - uses: giancosta86/aurora-github/actions/run-elvish-tests@v11
      with:
        working-directory: ${{ github.action_path }}
        velvet-scripts: check-main

    - shell: elvish {0}
      run: echo 🎭 Installing Velvet at tag ${{ env.expected-tag }}...

    - uses: ./actions/install-elvish-packages
      with:
        packages: github.com/giancosta86/velvet@${{ env.expected-tag }}

    - uses: giancosta86/aurora-github/actions/run-elvish-tests@v11
      with:
        working-directory: ${{ github.action_path }}
        velvet-scripts: check-tag

    - shell: elvish {0}
      run: echo 🎭 Installing multiple packages...

    - uses: ./actions/install-elvish-packages
      with:
        packages: github.com/giancosta86/primrose, github.com/giancosta86/astral-bridge

    - uses: giancosta86/aurora-github/actions/run-elvish-tests@v11
      with:
        working-directory: ${{ github.action_path }}
        velvet-scripts: check-multiple

    - shell: elvish {0}
      run: echo 🎭 Trying to re-install multiple packages...

    - uses: ./actions/install-elvish-packages
      with:
        packages: github.com/giancosta86/primrose, github.com/giancosta86/astral-bridge

    - shell: elvish {0}
      run: |
        echo ✅ Re-installation attempt performed!

    - shell: bash
      working-directory: ${{ github.action_path }}
      run: elvish setup-metadata.elv

    - shell: elvish {0}
      run: echo 🎭 Performing a metadata-driven install...

    - uses: ./actions/install-elvish-packages
      with:
        working-directory: ${{ env.temp-project-dir }}

    - uses: giancosta86/aurora-github/actions/run-elvish-tests@v11
      with:
        working-directory: ${{ github.action_path }}
        velvet-scripts: check-metadata-driven
